### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by baamelyoussef** [ippsav/Dinoly#8]
#4 Cors error when starting models. makhedma mawalou

**Comment by ippsav** [comment]
Starting models -> cors error, i don't see any cause for the issue, unless you're starting the server without specifying the environment variable, make sure when you run the init script to export POSTGRES_DB=dinoly-db before running it.

**Comment by baamelyoussef** [comment]
Fixed. Tbarkellah 3la Dinoly
