### ISSUE TITLE
Consider adding Dinoly to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [ippsav/Dinoly#9]
Hey @ippsav, thanks for adopting SeaORM! 
It's our pleasure to see more inspirational projects were built on top of SeaORM :) 

Let us know if you have any [feature recommendation](https://github.com/SeaQL/sea-orm/issues/new/choose) or [feedback](https://github.com/SeaQL/sea-orm/discussions/new). Your contribution is what drive us forward! 

Some learning resources for you: [Documentation](https://www.sea-ql.org/SeaORM/), [Tutorial](https://www.sea-ql.org/sea-orm-tutorial/), [Cookbook](https://www.sea-ql.org/sea-orm-cookbook/), [Q&A](https://github.com/SeaQL/sea-orm/discussions) 
Join our [Discord server](https://discord.com/invite/uCPdDXzbdv) to chat with others in the SeaQL community! 

Feel free to submit a PR to showcase your project, https://github.com/SeaQL/sea-orm/issues/403.

**Comment by ippsav** [comment]
I greatly appreciate your feedback. Utilizing SeaORM was a pleasant experience and the documentation was clear and easy to follow. I have been recommending it to others when selecting an ORM in Rust. I will be submitting a pull request soon and will also be adding some additional functionality to complete the project.

**Comment by billy1624** [comment]
Thanks for the love and support!! @ippsav
